version: "2"
plugins:
  git-legal:
    enabled: true
exclude_patterns:
  - "docs/"
  - "tests/"
  - "*/brewlog/_version.py"
  - "*/brewlog/cli.py"
  - "*/brewlog/wsgi.py"
  - "*/brewlog/config*.py"
  - "*/brewlog/app.py"
  - "*/brewlog/ext.py"
  - "*/brewlog/templates.py"
  - "*/brewlog/__init__.py"
  - "manage.py"
  - "setup.py"
  - "secrets/"
  - "**/static/"
  - "**/translations/*"
  - "**/templates/*"
checks:
  argument-count:
    config:
      threshold: 8
  method-complexity:
    config:
      threshold: 10
