verssion: "2"
plugins:
  bandit:
    enabled: true
  sonar-python:
    enabled: true
    config:
      test_patterns:
        - tests/**
exclude_patterns:
  - "tests/"
  - "*/_version.py"
  - "*/wsgi.py"
  - "*/config*.py"
  - "*/app.py"
  - "*/ext.py"
  - "*/templates.py"
  - "*/__init__.py"
  - "versioneer.py"
  - "manage.py"
  - "secrets/"
  - "**/static/"
