application: brew-log
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "30d"

handlers:
- url: /(favicon\.ico)
  static_files: static/\1
  upload: static/favicon\.ico

- url: /(robots\.txt)
  static_files: static/\1
  upload: static/robots\.txt

- url: /static
  static_dir: static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: setuptools
  version: "latest"
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.sublime*
- ^(.*/)?.*\.sh
