"""Up

Revision ID: 1234e73f7ae1
Revises: 156483c59b33
Create Date: 2014-04-17 15:32:54.232538

"""

# revision identifiers, used by Alembic.
revision = '1234e73f7ae1'
down_revision = '156483c59b33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fermentation_step', 'is_last')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentation_step', sa.Column('is_last', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
