"""Up

Revision ID: 156483c59b33
Revises: 4b42be3f877b
Create Date: 2014-04-16 22:52:35.495370

"""

# revision identifiers, used by Alembic.
revision = '156483c59b33'
down_revision = '4b42be3f877b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brew_date_brewed'), 'brew', ['date_brewed'], unique=False)
    op.create_index(op.f('ix_brew_updated'), 'brew', ['updated'], unique=False)
    op.create_index(op.f('ix_brewer_profile_email'), 'brewer_profile', ['email'], unique=False)
    op.create_index(op.f('ix_brewer_profile_updated'), 'brewer_profile', ['updated'], unique=False)
    op.create_index('user_remote_id', 'brewer_profile', ['oauth_service', 'remote_userid'], unique=False)
    op.create_index(op.f('ix_brewery_updated'), 'brewery', ['updated'], unique=False)
    op.create_index('user_label_template', 'custom_label_template', ['user_id', 'name'], unique=False)
    op.create_index(op.f('ix_fermentation_step_date'), 'fermentation_step', ['date'], unique=False)
    op.create_index('ipb_user_service', 'ipboard_export_setup', ['user_id', 'service_name'], unique=False)
    op.create_index(op.f('ix_tasting_note_date'), 'tasting_note', ['date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasting_note_date'), table_name='tasting_note')
    op.drop_index('ipb_user_service', table_name='ipboard_export_setup')
    op.drop_index(op.f('ix_fermentation_step_date'), table_name='fermentation_step')
    op.drop_index('user_label_template', table_name='custom_label_template')
    op.drop_index(op.f('ix_brewery_updated'), table_name='brewery')
    op.drop_index('user_remote_id', table_name='brewer_profile')
    op.drop_index(op.f('ix_brewer_profile_updated'), table_name='brewer_profile')
    op.drop_index(op.f('ix_brewer_profile_email'), table_name='brewer_profile')
    op.drop_index(op.f('ix_brew_updated'), table_name='brew')
    op.drop_index(op.f('ix_brew_date_brewed'), table_name='brew')
    ### end Alembic commands ###
