"""default marker for custom export template

Revision ID: 1b5f869f571a
Revises: 451c2e4e9d37
Create Date: 2013-09-18 12:35:17.507946

"""

# revision identifiers, used by Alembic.
revision = '1b5f869f571a'
down_revision = '451c2e4e9d37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_export_template', sa.Column('is_default', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_export_template', 'is_default')
    ### end Alembic commands ###
