"""index for fermentation step

Revision ID: 25802f067902
Revises: 44643242c85b
Create Date: 2013-10-25 09:50:52.055234

"""

# revision identifiers, used by Alembic.
revision = '25802f067902'
down_revision = '44643242c85b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fermentationstep_brew_date', 'fermentation_step', ['brew_id', 'date'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fermentationstep_brew_date', 'fermentation_step')
    ### end Alembic commands ###
