"""stats field for brewery

Revision ID: 3385a2c73d01
Revises: 1b5f869f571a
Create Date: 2013-10-04 10:43:46.562790

"""

# revision identifiers, used by Alembic.
revision = '3385a2c73d01'
down_revision = '1b5f869f571a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewery', sa.Column('stats', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brewery', 'stats')
    ### end Alembic commands ###
