"""Up

Revision ID: 44dabbe59bd6
Revises: 1234e73f7ae1
Create Date: 2014-04-26 22:43:15.189731

"""

# revision identifiers, used by Alembic.
revision = '44dabbe59bd6'
down_revision = '1234e73f7ae1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brew', 'og')
    op.drop_column('brew', 'brew_length')
    op.drop_column('brew', 'fg')
    op.drop_column('brew', 'fermentation_temperature')
    op.drop_column('brew', 'fermentation_start_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brew', sa.Column('fermentation_start_date', sa.DATE(), nullable=True))
    op.add_column('brew', sa.Column('fermentation_temperature', sa.INTEGER(), nullable=True))
    op.add_column('brew', sa.Column('fg', sa.REAL(), nullable=True))
    op.add_column('brew', sa.Column('brew_length', sa.REAL(), nullable=True))
    op.add_column('brew', sa.Column('og', sa.REAL(), nullable=True))
    ### end Alembic commands ###
