"""empty message

Revision ID: 451c2e4e9d37
Revises: None
Create Date: 2013-08-07 11:44:46.509571

"""

# revision identifiers, used by Alembic.
revision = '451c2e4e9d37'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brewer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('nick', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('oauth_token', sa.Text(), nullable=True),
    sa.Column('oauth_token_secret', sa.Text(), nullable=True),
    sa.Column('oauth_service', sa.String(length=50), nullable=True),
    sa.Column('remote_userid', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipboard_export_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['brewer_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_export_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['brewer_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brewery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('est_year', sa.Integer(), nullable=True),
    sa.Column('est_month', sa.Integer(), nullable=True),
    sa.Column('est_day', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('brewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brewer_id'], ['brewer_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    carbtype_enum = sa.Enum(u'forced in keg', u'keg with priming', u'bottles with priming', name='enum_carbtype')
    carblevel_enum = sa.Enum(u'high', u'normal', u'low', u'very low', u'none', name='enum_carblevel')
    op.create_table('brew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=200), nullable=True),
    sa.Column('bjcp_style_code', sa.String(length=20), nullable=True),
    sa.Column('bjcp_style_name', sa.String(length=50), nullable=True),
    sa.Column('bjcp_style', sa.String(length=100), nullable=True),
    sa.Column('date_brewed', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('notes_html', sa.Text(), nullable=True),
    sa.Column('fermentables', sa.Text(), nullable=True),
    sa.Column('hops', sa.Text(), nullable=True),
    sa.Column('yeast', sa.Text(), nullable=True),
    sa.Column('misc', sa.Text(), nullable=True),
    sa.Column('mash_steps', sa.Text(), nullable=True),
    sa.Column('sparging', sa.String(length=200), nullable=True),
    sa.Column('hopping_steps', sa.Text(), nullable=True),
    sa.Column('fermentation_steps', sa.Text(), nullable=True),
    sa.Column('boil_time', sa.Integer(), nullable=True),
    sa.Column('fermentation_start_date', sa.Date(), nullable=True),
    sa.Column('og', sa.Float(precision=1), nullable=True),
    sa.Column('fg', sa.Float(precision=1), nullable=True),
    sa.Column('abv', sa.Float(precision=1), nullable=True),
    sa.Column('brew_length', sa.Float(precision=2), nullable=True),
    sa.Column('fermentation_temperature', sa.Integer(), nullable=True),
    sa.Column('final_amount', sa.Float(precision=2), nullable=True),
    sa.Column('bottling_date', sa.Date(), nullable=True),
    sa.Column('carbonation_type', carbtype_enum, nullable=True),
    sa.Column('carbonation_level', carblevel_enum, nullable=True),
    sa.Column('carbonation_used', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('brewery_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brewery_id'], ['brewery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fermentation_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('og', sa.Float(precision=1), nullable=True),
    sa.Column('fg', sa.Float(precision=1), nullable=True),
    sa.Column('is_last', sa.Boolean(), nullable=True),
    sa.Column('brew_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brew_id'], ['brew.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasting_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_html', sa.Text(), nullable=True),
    sa.Column('brew_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['brewer_profile.id'], ),
    sa.ForeignKeyConstraint(['brew_id'], ['brew.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasting_note')
    op.drop_table('fermentation_step')
    op.drop_table('brew')
    op.drop_table('brewery')
    op.drop_table('custom_export_template')
    op.drop_table('ipboard_export_setup')
    op.drop_table('brewer_profile')
    ### end Alembic commands ###
