"""fermentation data for step

Revision ID: 4adad2975206
Revises: 47fdd72c6bb3
Create Date: 2013-10-18 10:18:10.727473

"""

# revision identifiers, used by Alembic.
revision = '4adad2975206'
down_revision = '47fdd72c6bb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentation_step', sa.Column('temperature', sa.Integer(), nullable=True))
    op.add_column('fermentation_step', sa.Column('volume', sa.Float(precision=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fermentation_step', 'volume')
    op.drop_column('fermentation_step', 'temperature')
    ### end Alembic commands ###
