"""typo in column name

Revision ID: 4b42be3f877b
Revises: 25802f067902
Create Date: 2013-10-28 09:57:13.306340

"""

# revision identifiers, used by Alembic.
revision = '4b42be3f877b'
down_revision = '25802f067902'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentation_step', sa.Column('notes_html', sa.Text(), nullable=True))
    op.drop_column('fermentation_step', u'hotes_html')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentation_step', sa.Column(u'hotes_html', mysql.TEXT(), nullable=True))
    op.drop_column('fermentation_step', 'notes_html')
    ### end Alembic commands ###
