"""fermentation step name and notes

Revision ID: 512342cf34e3
Revises: 3385a2c73d01
Create Date: 2013-10-06 11:37:12.570719

"""

# revision identifiers, used by Alembic.
revision = '512342cf34e3'
down_revision = '3385a2c73d01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentation_step', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('fermentation_step', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('fermentation_step', sa.Column('notes_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fermentation_step', 'notes_html')
    op.drop_column('fermentation_step', 'notes')
    op.drop_column('fermentation_step', 'name')
    ### end Alembic commands ###
