import os

PROPAGATE_EXCEPTIONS = True

MYSQL_HOST = os.environ['OPENSHIFT_MYSQL_DB_HOST']
MYSQL_PORT = os.environ['OPENSHIFT_MYSQL_DB_PORT']
MYSQL_USER_NAME = os.environ['OPENSHIFT_MYSQL_DB_USERAME']
MYSQL_PASSWORD = os.environ['OPENSHIFT_MYSQL_DB_PASSWORD']
MYSQL_DB_NAME = 'brewlog'
MYSQL_SOCKET = os.environ['OPENSHIFT_MYSQL_DB_SOCKET']

SQLALCHEMY_DATABASE_URI = 'mysql://%(MYSQL_USER_NAME)s:%(MYSQL_PASSWORD)s@%(MYSQL_HOST)s:%(MYSQL_PORT)s/%(MYSQL_DB_NAME)s?charset=utf8' % locals()
PROD_SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI

UPLOAD_DIR = os.path.join(os.environ['OPENSHIFT_DATA_DIR'], 'uploads')
