"""empty message

Revision ID: 5777779293a6
Revises: 
Create Date: 2019-08-25 14:08:07.425547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5777779293a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewer_profile', sa.Column('confirmation_sent_dt', sa.DateTime(), nullable=True))
    op.add_column('brewer_profile', sa.Column('confirmed_dt', sa.DateTime(), nullable=True))
    op.add_column('brewer_profile', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('brewer_profile', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('brewer_profile', sa.Column('username', sa.String(length=200), nullable=True))
    op.alter_column('brewer_profile', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_index(op.f('ix_brewer_profile_username'), 'brewer_profile', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brewer_profile_username'), table_name='brewer_profile')
    op.alter_column('brewer_profile', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('brewer_profile', 'username')
    op.drop_column('brewer_profile', 'password')
    op.drop_column('brewer_profile', 'email_confirmed')
    op.drop_column('brewer_profile', 'confirmed_dt')
    op.drop_column('brewer_profile', 'confirmation_sent_dt')
    # ### end Alembic commands ###
