name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [3.7, 3.8]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install -U -q pip wheel
          python -m pip install -U -q -e .[test]
      - name: Get PIP cache dir
        id: pip-cache-dir
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: pip|${{ matrix.python }}|${{ hashFiles('setup.py') }}
      - name: Run tests
        run: |
          python -m pytest --cov-branch --cov brewlog tests
      - name: Test package build
        run: |
          python setup.py -q sdist bdist_wheel
      - name: Coveralls report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          python -m pip install -U -q coveralls
          coveralls
